site_name: LPJ EOSIM
site_url: https://lpj-eosim.github.io
repo_url: https://github.com/LPJ-EOSIM/lpj-eosim.github.io

nav:
  - Home: index.md
  - Usage:
      - Simulations: simulations.md
  - Benchmarks:
      - "Incorporating a nitrogen cycle in LPJ-EOSIM": results/pr-412.md
      - "PR #421": results/pr-421.md
      - "SPITFIRE in LPJ-EOSIM (CRUJRA)": results/spitfire.md
      - "ERA5 low-latency runs": results/era5.md
  - Publications: publications.md

plugins:
  - search  # Enables site search
  - mkdocstrings  # Generates API docs from docstrings

markdown_extensions:
  - admonition  # Adds note/warning/info boxes
  - toc:  # Table of contents
      permalink: true
      
# Configuration
theme:
  highlightjs: true
  name: 'material'
  repo_url: null 
